// <auto-generated />
namespace WpfApp_cf_ef_kitapevi_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class yeni_iliski : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yeni_iliski));
        
        string IMigrationMetadata.Id
        {
            get { return "201505220319522_yeni_iliski"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
